### ISSUE TITLE
Implement the FAQ page with dummy data.

### ISSUE THREAD

**Issue by clr-rtc** [clr-rtc/blog-nextjs-sanity#4]
There is now a dummy FAQ french page at: http://localhost:3000/pages/faq

It does not appear in the menu and there is no english version. The content is hardcoded. 
The page itself is in ~/pages/pages/faq.tsx and there is some dummy data defined there that can be modified as needed as development progresses.

It uses a component in ~/components/FaqPage.tsx to do the actual rendering. Modify that to change the appearance and definition of the FAQ items.

Once you create dummy data you like and have the desired appearance, checkin this code to the faq branch.

Go into the FaqPage.tsx and modify the HTML to produce the appearance that you want. The current appearance is just a silly placeholder. Now you can go and do things like create a title versus the actual answer, set the colors, fonts, add other stuff as makes sense (last update?). In order to display more things, modify the FaqItem type in this file to include the additional pieces of information that you need. Then go back to where the dummy data is defined in the main file faq.tsx and add the extra information. Repeat until you have a good mockup of the FAQ page that you like the appearance of.

Another item will follow to save and retrieve the FAQ items from the Sanity CMS database.

To start working on it, choose the faq branch instead of main in source control. Then do Pull to get the latest changes. 
When you're ready to checkin, the code will first go to the faq branch, then you'll do a pull request to get it reviewed and merged into main.

**Comment by clr-rtc** [comment]
Don't forget to ask CoPilot if you're not sure how to do the git steps! Also you can't checkin directly to main because of safety permissions, so don't worry about anything. I already put the started changes on main so if we needed to delete the faq branch, we could do it without losing anything.

**Comment by martinbechard** [comment]
Good work on this first item, it's looking good in production!
